### ISSUE TITLE
Gear generation is slow.

### ISSUE THREAD

**Issue by GarryBGoode** [GarryBGoode/py_gearworks#4]
Raising this issue to document and keep track of speed problems.

Testing the 'fishbone_bevel' example, which stresses the core quite a bit, this is the timing results I got:

- Gear stack generation took 6.582513809204102 seconds
- Nurb generation took 9.074028015136719 seconds
- Surface generation took 4.544015407562256 seconds
- total gear build time: 23.2147452831268

(by subtraction, the build123d conversion took about 3s).

This example generated 2x11 2D gear profiles, converted all of them to NURBS, and then converted 2 surface-ribbons out the NURBS.

Surface generation has a "slow" and "fast" method. The fast method completes in 0.7s vs 4.5s for the slow.
The fast method is expected to be less accurate, but not sure if some tradeoff here is still worth it. Maybe 1 order higher is still faster?

The largest chunk of time is spent on NURBS conversion. Not sure which part of this is slow, possibly the solver, but...
The tooth involute and the undercut trochoid are converted with solver. The other curves are lines and arcs that have exact solution to convert to NURB. Disabling the undercut reduces conversion time from 9s to 7.5s. If the solver is such major contributor to speed this boost should have been way more, maybe at least 3s. More investigation needed... is it the length calculations???

**Comment by GarryBGoode** [comment]
Attempts at general speedup:

parallelization:
In theory this whole thing should be well parallelized. 22 gear-profiles are generated and converted to NURB in a sequence... In practice, all these function calls happen inside multiple layers of classes and class-method calls and multiprocessing keeps complaining about not being able to pickle them.

c-compilation with numba jit:
I tried applying numba but it proves difficult. It won't touch scipy stuff like root and minimize, and all my math functions are written to be flexible with array dimensions, which seems to be a general issue for numba. It tends to stumble on the numpy array shape and dimension manipulations before the calculations happen.

**Comment by GarryBGoode** [comment]
Another experiment: 
Lenght approximation N was changed from 101 to 11 as a test, results:
gear generation: 6.6s -> 3s 
nurb generation: 9s -> 8.75s

Are length params being updated too often? Maybe try caching? Is this resolution necessary?
Also it is less likely that nurb conversion suffers because of the length updaters.

**Comment by GarryBGoode** [comment]
Developed NURBS analytic derivatives to try and enhance curve-to-nurbs conversion results.
Managed to make it numpy friendly with lots of array-matrix operations.

BFGS minimize method seems to be the best so far. 
It needs the same number of iterations with or without jac (derivative), but if jac is given, it is maybe 10% faster (2.4s vs 2.7s).

Tested CG method, much worse than BFGS, 2~3x as slow.
Tested TNC, 2x as fast as BFGS but leaves 100x more error (final cost value ~1E-6 vs. ~1E-8). Maybe tolerances can be tweaked so that it goes further... 

Using combined cost-derivative function (both in the same function) did not make noticeable difference.

Seems like staying on BFGS with derivative is the best way forward.

**Comment by KilowattSynthesis** [comment]
Just wanted to throw out another idea, which is obviously less good than fixing the problem at its root, but which may still be worth mentioning: you could add a caching mechanism. All inputs to gear generation steps would be tracked and hashed, and then the generation result (serialized) could be stored in a user-specified cache directory (or default to `~/.cache/gggears/build/`). Would allow faster builds on certain parts, presumably. I also wonder if there are any hot-path steps that could use an in-memory cache decorator as-is?

**Comment by GarryBGoode** [comment]
@kcleung 

I think it could help if you could give it a shot.
This is the result of my current quick-test on the `fishbone_bevels()` example in `examples.py`
```
2025-01-14 22:45:48,060 - INFO - Gears generated in 2.67282 seconds
2025-01-14 22:45:49,709 - INFO - Nurbs generated in 1.64844 seconds
2025-01-14 22:45:51,303 - INFO - Surfaces generated in 1.59391 seconds
gear build time: 10.302504539489746
```
The first 3 items are the stuff I did in python, the rest of the total time is build123d / OCCT operations, about 4.2s.
You can see that even with great optimization and parallelization we can get a 60% boost at best (at least on this example). I don't think there's much to be gained on the OCCT part, as far as I can see it is loading all my CPU cores already. But maybe you can try something...

The gear generation and NURB generation is where I see the most potential of parallelization. There's some input-parameter setup, and then these 'stacks' of gear-curves with NURB parameters are generated in simple for... iterators. These are the `generate_gear_stacks()` and `generate_nurbs()` methods in `gggears_convert.py`. The 2 functions probably should be merged into 1, but I do need to have both kind of 'stacks' in the end, they're used elsewhere.

I realize many of my classes could be just functions, if that's necessary I'll look into refactoring them, but that is probably quite a lot of work. But if you need it, and maybe you can do it with relatively low-impact, it's OK to do so

The surface generation part is one large-ish minimize operation on the NURB points and weights. Maybe you could try that parallel-minimize thing with it.

**Comment by kcleung** [comment]
I have just tried to run example.py but it comes with the following errors:

2025-01-15 23:16:01,444 - INFO - None context requested by None
2025-01-15 23:16:01,444 - INFO - Entering BuildPart with mode=Mode.ADD which is in different scope as parent
2025-01-15 23:16:01,444 - INFO - WorkplaneList is pushing 1 workplanes: [Plane(o=(0.00, 0.00, 0.00), x=(1.00, 0.00, 0.00), z=(0.00, 0.00, 1.00))]
2025-01-15 23:16:01,447 - INFO - LocationList is pushing 1 points: [(p=(0.00, 0.00, 0.00), o=(-0.00, 0.00, -0.00))]
2025-01-15 23:16:02,792 - INFO - Gears generated in 1.34363 seconds
2025-01-15 23:16:03,706 - INFO - Nurbs generated in 0.91332 seconds
2025-01-15 23:16:04,780 - INFO - Surfaces generated in 1.07432 seconds
2025-01-15 23:16:05,899 - INFO - LocationList is popping 1 points
2025-01-15 23:16:05,900 - INFO - WorkplaneList is popping 1 workplanes
2025-01-15 23:16:05,900 - INFO - Exiting BuildPart
Traceback (most recent call last):
  File "c:\Users\git\gggears\examples\examples.py", line 376, in <module>
    show(bevel_gear(), deviation=0.05, angular_tolerance=0.1)
         ~~~~~~~~~~^^
  File "c:\Users\git\gggears\examples\examples.py", line 173, in bevel_gear
    gear1.build_part()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\AppData\Local\miniconda3\envs\ocp-cad-viewer\Lib\site-packages\gggears\gggears_wrapper.py", line 580, in build_part
    self.builder = GearBuilder(
                   ~~~~~~~~~~~^
        self.gearcore,
        ^^^^^^^^^^^^^^
    ...<2 lines>...
        method="slow",
        ^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\AppData\Local\miniconda3\envs\ocp-cad-viewer\Lib\site-packages\gggears\gggears_build123d.py", line 121, in __init__
    side_surfaces = self.gen_side_surfaces(only_outside_surface=True)
  File "C:\Users\AppData\Local\miniconda3\envs\ocp-cad-viewer\Lib\site-packages\gggears\gggears_build123d.py", line 220, in gen_side_surfaces
    tooth_surface_rot = tooth_surface.rotate(
                        ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ShapeList' object has no attribute 'rotate'

The same error occured when I tried to run the other test file test_gear.py

What could have gone wrong?

**Comment by GarryBGoode** [comment]
@kcleung 

What version of build123d are you using?
My local env is 
* python3.12.8
* build123d==0.8.0
* cadquery-ocp==7.7.2
* ocp_vscode==2.6.1
* numpy==2.2.1
* scipy==1.15.0

The git test environment tests python 3.9 to 3.11 I think, with build123d 0.8.0 + dependencies.

I think I ran into something like that when I had somehow build123d 0.8.1, but not sure.

**Comment by GarryBGoode** [comment]
I can confirm the issue comes up with the dev branch of build123d. They did a big refactor I'll need to comply with, I'm trying to work out the kinks.

In the meantime please use build123d 0.8.0.

**Comment by kcleung** [comment]
> I can confirm the issue comes up with the dev branch of build123d. They did a big refactor I'll need to comply with, I'm trying to work out the kinks.
> 
> In the meantime please use build123d 0.8.0.

Do you want me to have a crack at getting gggear to work with build123d 0.8.1+ and then look at speedup issues with the refactored code once for all?  By working on the code first, this process will also force me to familiarize myself with the gggears and build123d code, which is essential for me to get to know the algorithm, and therefore potential performance bottlenecks.

If so, I just had a look at the code.  The problem is that in GearBuilder::gen_side_services(), at line 218 of gggears_build123d.py it calls 

tooth_surface = Face.fuse(*tooth_surfaces[:-3])

Face.fuse() fuse the tooth surfaces, except the last three, into one single surface.  This returns either a Shape object, or if multiple non-compound objects are called, then ShapeList is returned instead.

Only the class Shape has the rotate() method, but obviously ShapeList hasn't.

In the test case, when Face.fuse ends up returning a ShapeList, then at line 220 of gggears_build123d.py it tries to rotate the rotate() on tooth_surface, which happens to be a ShapeList instead of a Shape, then obviously it will throw an exception.

Can you please enlighten me under what circumstances can Face.fuse() return a list of shapes, instead of a single shape of fused tooth shapes?

**Comment by GarryBGoode** [comment]
@kcleung 

I went into this problem already, put up a new branch about it, probably around the time you wrote this.

The whole CAD builder stuff was big mess, which I made, and I'd like to clean it up myself (at least a little bit).

The idea behind those Face.fuse() steps was to try and make it easier for the OCT algorithm, I thought it made sense if fusion happens in somewhat structured chunks.

Turns out it makes no difference. It seems there is no low-level fusion of Face objects, they just get put into a list or container of sorts. The build123d devs moved stuff around and refactored and now it's a different kind of container than before. That's how it ended up being a ShapeList, while previously it was maybe Compound, not sure.

So I simplified and removed a lot of stuff. There was also old code about 'projection'. It's an alternative method of constructing the top/bottom face, I'm removing that as well, the current 'split' method seems to be robust enough.

So the current status of `GearBuilder` is not great, but better. That `surfaces[:-3]` is also super magical that I'd like to deal with. It's just that the converter deals with a 'closed' profile of 1 tooth, the last 3 lines/patches go around to close it, but I don't need those here.

Looong story short please try the branch `CAD_refactor_and_bd_090_compliance`, and look into `gggears_convert.py` for parallelization efforts. Let me work on the CAD stuff.

**Comment by kcleung** [comment]
> [@kcleung](https://github.com/kcleung)
> 
> I went into this problem already, put up a new branch about it, probably around the time you wrote this.
> 
> The whole CAD builder stuff was big mess, which I made, and I'd like to clean it up myself (at least a little bit).
> 
> The idea behind those Face.fuse() steps was to try and make it easier for the OCT algorithm, I thought it made sense if fusion happens in somewhat structured chunks.
> 
> Turns out it makes no difference. It seems there is no low-level fusion of Face objects, they just get put into a list or container of sorts. The build123d devs moved stuff around and refactored and now it's a different kind of container than before. That's how it ended up being a ShapeList, while previously it was maybe Compound, not sure.
> 
> So I simplified and removed a lot of stuff. There was also old code about 'projection'. It's an alternative method of constructing the top/bottom face, I'm removing that as well, the current 'split' method seems to be robust enough.
> 
> So the current status of `GearBuilder` is not great, but better. That `surfaces[:-3]` is also super magical that I'd like to deal with. It's just that the converter deals with a 'closed' profile of 1 tooth, the last 3 lines/patches go around to close it, but I don't need those here.
> 
> Looong story short please try the branch `CAD_refactor_and_bd_090_compliance`, and look into `gggears_convert.py` for parallelization efforts. Let me work on the CAD stuff.

Just tried your new branch.  build123d also renamed Keep.ALL with Keep.BOTH 

At the moment, line 123 of gggears_build123d.py needs to be fixed, though there may be others.

I am about to look at gggears_convert.py

**Comment by GarryBGoode** [comment]
I'm confused, what version of build123d did you use?
I'm on the latest `dev` version for this, the ALL option is there, though they added it quite recently.

**Comment by kcleung** [comment]
> I'm confused, what version of build123d did you use? I'm on the latest `dev` version for this, the ALL option is there, though they added it quite recently.

Ahhhhhh sorry I forgot to pull.  All sorted.

example.py now runs successfully.

I have just had a look at gggears_convert.py

It appears that GearToNurbs::generate_nurbs() and GearToNurbs::generate_surface_point_() have for loops which appears to be embarassingly parallel with consistent workload.

In the for loops in both cases, each iteration writes to its corresponding element in the output array by append().

Is it okay if I define a fixed-size output array, and let the iteration directly write to its element output[i] instead?  This will make the interpreter easier to determine parallelization.

Sorry for my ignorance in python...... I main programmed in C++

**Comment by GarryBGoode** [comment]
Yes, it's OK however you rewrite them provided 
1: I understand it after reviewing it, and 
2: the tests pass and the examples still work afterward, and
3: preferably the parallelization should be possible to be switched/configured off, should it cause issues on - I dunno - ARM Windows or something.

I'm not that proficient, or picky with python style either. Here I was lazy and doing it in a dumb beginner-ish way.

**Comment by GarryBGoode** [comment]
Although the size does vary case-by-case depending on the gear type, number of samples, etc.
Is that an issue? Does it need to be totally predefined, like in a global const?
